apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spring-boot-podmonitor
  namespace: monitoring
  labels:
    release: prometheus  # Adjust based on your Prometheus Operator setup
spec:
  selector:
    matchLabels:
      project: spring
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
