spring:
  application:
    name: latency-measurement-service
server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    export:
      prometheus:
        enabled: true