spring:
  application:
    name: binance-websocket-service
server:
  port: 8081
nats:
  url: ${NATS_URL:nats://localhost:4222}
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    export:
      prometheus:
        enabled: true