apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-latency-measurement-service-nats
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      project: spring
      app: binance-latency-measurement-service-nats
  template:
    metadata:
      labels:
        project: spring
        app: binance-latency-measurement-service-nats
    spec:
      containers:
        - name: binance-latency-measurement-service-nats
          image: cefothe/binance-latency-measurement-service-nats:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: NATS_URL
              value: "nats://nats:4222"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: latency-measurement-service-kafka
                topologyKey: "kubernetes.io/hostname"